In [1]:
%matplotlib inline
import numpy as np
import pandas as pd

import viz # curriculum example visualizations

np.random.seed(1349)

In [ ]:
How likely is it that you roll doubles when rolling two dice?

In [108]:
roll_percent = (1/6)
n_trials = nrows = 10_000 
n_dice = ncols = 2

rolls = np.random.choice([1,2,3,4,5,6], n_trials * n_dice).reshape(nrows, ncols)

In [109]:
rolls

array([[4, 3],
       [2, 2],
       [6, 5],
       ...,
       [3, 2],
       [5, 2],
       [5, 4]])

In [183]:
sum_rolls = (rolls.sum(axis=1) < roll_percent).mean()

In [184]:
sum_rolls

0.0

If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting more than 3 heads?

In [40]:
p_flip = 0.5
n_trials = nrows = 10_000 
n_coins = ncols = 8

flips = np.random.random((nrows, ncols))

In [42]:
heads = flips > 0.5

In [43]:
heads

array([[False,  True,  True, ..., False, False,  True],
       [False,  True,  True, ..., False,  True,  True],
       [ True,  True,  True, ...,  True,  True, False],
       ...,
       [False, False, False, ...,  True,  True, False],
       [ True, False, False, ..., False, False, False],
       [ True,  True, False, ..., False, False,  True]])

In [51]:
print(f"The percentage of getting exactly 3 heads is {round(((heads.sum(axis=1) == 3).mean() * 100),2)}")

The percentage of getting exactly 3 heads is 21.35


In [168]:
print(f"The percentage of getting more than 3 heads is {round(((heads.sum(axis=1) >= 3).mean() * 100),2)}")

The percentage of getting more than 3 heads is 85.06


There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?

In [170]:
ds_cohort = 0.25
n_trials = nrows = 10_000 
n_billboards = ncols = 2

billboards = np.random.random((nrows, ncols))

In [171]:
billboards

array([[0.05881881, 0.96685527],
       [0.77346827, 0.92009251],
       [0.41344069, 0.29063038],
       ...,
       [0.16189809, 0.31054492],
       [0.692728  , 0.78642676],
       [0.20965895, 0.91975709]])

In [172]:
total_billboards = billboards < ds_cohort

In [173]:
total_billboards


array([[ True, False],
       [False, False],
       [False, False],
       ...,
       [ True, False],
       [False, False],
       [ True, False]])

In [174]:
(total_billboards.sum(axis=1) == 2).mean()

0.0608

In [175]:
print(f"The percentage of getting 2 billboards of DS students is {round(((total_billboards.sum(axis=1) == 2).mean() * 100),2)}")

The percentage of getting 2 billboards of DS students is 6.08


Codeup students buy, on average, 3 poptart packages (+- 1.5) a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon?

In [136]:
n_trials = n_rows = 10_000
n_days = n_cols = 5

testing = np.random.normal(3, 1.5, size =(n_trials, n_days))

In [137]:
testing_sums = testing.sum(axis=1)

In [140]:
yes_poptarts = (testing_sums < 17).mean()
print(f"There is a {yes_poptarts} chance at least 1 poptart will be available.")

There is a 0.7232 chance at least 1 poptart will be available.


Compare Heights

Men have an average height of 178 cm and standard deviation of 8cm.
Women have a mean of 170, sd = 6cm.
If a man and woman are chosen at random, P(woman taller than man)?


In [124]:
men_average_height = 178
men_std_dev = 8
women_average_height = 170
women_std_dev = 6
n_cols = 10 ** 6
men_array = np.random.normal(men_average_height, men_std_dev, n_cols).astype(int).reshape(n_cols, 1)
women_array = np.random.normal(women_average_height, women_std_dev, n_cols).astype(int).reshape(n_cols, 1)

In [125]:
men_array

array([[175],
       [175],
       [178],
       ...,
       [174],
       [174],
       [171]])

In [126]:
women_array

array([[175],
       [170],
       [164],
       ...,
       [166],
       [164],
       [170]])

In [145]:
diff_array = men_array - women_array
diff_array

array([[ 0],
       [ 5],
       [14],
       ...,
       [ 8],
       [10],
       [ 1]])

In [146]:
taller_women = (diff_array < 0).mean()

In [149]:
print(f"The probability of women who are taller than men are: {taller_women}")

The probability of women who are taller than men are: 0.197639


In [ ]:
When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the 
installation fails. What are the odds that after having 50 students download anaconda, no one has an installation 
issue? 100 students?

What is the probability that we observe an installation issue within the first 150 students that download anaconda?

How likely is it that 450 students all download anaconda without an issue?

In [152]:
is_corrupt = (1/250)
n_trials = nrows = 10_000 
n_students = ncols = 50
is_not_corrupt = (1 - is_corrupt)

rolls = np.random.choice([0,1], n_trials * n_students, p=[is_corrupt, is_not_corrupt]).reshape(nrows, ncols)

In [153]:
rolls

array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1]])

In [162]:
corrupted = (rolls).sum(axis=1)
corrupted_percentage = (corrupted < 50).mean()

In [163]:
corrupted_percentage

0.1891

In [176]:
is_corrupt = (1/250)
n_trials = nrows = 10_000 
n_students = ncols = 100
is_not_corrupt = (1 - is_corrupt)

rolls = np.random.choice([0,1], n_trials * n_students, p=[is_corrupt, is_not_corrupt]).reshape(nrows, ncols)

In [177]:
rolls

array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1]])

In [178]:
corrupted = (rolls).sum(axis=1)
corrupted_percentage = (corrupted < 100).mean()

In [179]:
corrupted_percentage

0.3307

There's a 70% chance on any given day that there will be at least one food truck at Travis Park. However, you haven't seen a food truck there in 3 days. How unlikely is this?

How likely is it that a food truck will show up sometime this week?

In [187]:
nrows = 10_000
ncols = 3
truck = 1
no_truck = 0
data = np.random.random((nrows, ncols))

In [190]:
((data < .7).sum(axis=1) == 0).mean()

0.0255

If 23 people are in the same room, what are the odds that two of them share a birthday? What if it's 20 people? 40?

In [92]:
birthday = (1/365)
n_trials = nrows = 10_000 
n_people = ncols = 23
n_birthdays = np.random.uniform(0, 365, n_trials * n_people).astype(int).reshape(nrows,ncols)

In [93]:
n_birthdays

array([[336, 214, 248, ..., 118, 316, 115],
       [302, 126, 262, ..., 145, 152, 198],
       [147, 239, 320, ...,  77,  60, 223],
       ...,
       [ 46,  48, 249, ...,  17, 180, 310],
       [132, 297, 123, ..., 304, 117, 213],
       [157, 353, 245, ..., 344, 232, 302]])

In [94]:
shared_birthday = (n_birthdays < birthday)

In [95]:
shared_birthday

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [164]:
birthdays = (shared_birthday).sum(axis=1)

In [193]:
shared_birthday_percentage = (birthdays < 40).mean()

In [194]:
shared_birthday_percentage

1.0